config/routes.rb
Rails.application.routes.draw do
  get 'password_edits/edit'
  root 'static_pages#home'
  get    '/signup', to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure',           to: 'users#auth_failure'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :password_edits, only: [:edit, :update]
  resources :microposts,     only: [:show, :create, :destroy]
  resources :microposts do
    resources :comments, only: [:create, :destroy]
  end
  resources :microposts do
    resource :favorites, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :micropost, optional: true
  belongs_to :comment, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  
  def index
    @notifications = current_user.passive_notifications.paginate(page: params[:page])
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
  
  def destroy
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
  
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
  
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<li>
  <div class="col-md-12 mx-auto">
    <div class="form-inline">
      <span>
        <%= link_to user_path(visitor) do %>
          <%= gravatar_for(visitor, size: 35) %>
          <strong>
            <%= visitor.user_name %>
          </strong>
        <% end %>
        <%= "さんが" %>
        
        <% case notification.action %>
          <% when 'follow' then %>
            <%= "あなたをフォローしました" %>
          <% when 'like' then %>
            <%= link_to "あなたの投稿", notification.micropost, style: "font-weight: bold;" %>
            <%= "にいいねしました。" %>
          <% when 'comment' then %>
              <%= link_to "あなたの投稿", notification.micropost, style: "font-weight: bold;" %>
            <%= "にコメントしました" %>
            <p class="text-muted mb-0">
              <%= Comment.find_by(id: notification.comment_id)&.content %>
            </p>
        <% end %>
        
      </span>
    </div>
    <div class="small text-muted text-right">
      <%= time_ago_in_words(notification.created_at) %> ago.
    </div>
  </div>
</li>

app/views/notifications/index.html.erb
<% provide(:title, 'Notifications') %>
<h1>Notifications</h1>
<!--自分の投稿へのいいね・コメントは除外する-->
<% notifications = @notifications.where.not(visitor_id: current_user.id) %>
<% if notifications.exists?  %>
  <div class="notifications">
    <%= render notifications %>
    <%= will_paginate notifications %>
    <%= link_to "Delete all notifications", notification_path(@notifications), method: :delete,
       data: { confirm: "Are you sure?" }, title: "Confirmation" %>
  </div>
<% else %>
  <p>通知はありません</p>
<% end %>