config/routes.rb
Rails.application.routes.draw do
  get 'password_edits/edit'
  root 'static_pages#home'
  get    '/signup', to: 'users#new'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure',           to: 'users#auth_failure'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :password_edits, only: [:edit, :update]
  resources :microposts,     only: [:show, :create, :destroy]
  resources :microposts do
    resources :comments, only: [:create, :destroy]
  end
  resources :microposts do
    resource :favorites, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: [:index, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy;2020 Memoryboard All rights reserved.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Memoryboard", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <% if logged_in? %>
        <!--↓ログイン状態でしか出ないメニュー-->
          <li>
            <%= link_to(notifications_path) do %>
              <% if unchecked_notifications.any? %>
                <i class="fa fa-bell fa-lg" aria-hidden="true"></i>
                <i class="fa fa-circle notification-circle circle-small"></i>
              <% else %>
                <i class="fa fa-bell" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </li>
          
          <li><%= link_to "Users", users_path %></li>
          
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Page", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
             
          <% if current_page?(users_path) || current_page?(notifications_path) %>
            <li>
              <%= form_tag(users_path,:method => 'get', class: "serach-window") do %>
                <%= text_field_tag :search, '', placeholder: 'user' %>
                <%= submit_tag 'Search', :name => nil %>
              <% end %>
            </li>
          <% elsif current_page?(root_path) || current_page?(new_micropost_path) %>
            <li>
              <%= form_tag(root_path,:method => 'get', class: "serach-window") do %>
                <%= text_field_tag :search, '', placeholder: 'comment' %>
                <%= submit_tag 'Search', :name => nil %>
              <% end %>
            </li>
          <% elsif current_page?(:controller => 'users', :action => 'show', :id => params[:id]) %>
            <li>
              <%= form_tag(user_path,:method => 'get', class: "serach-window") do %>
                <%= text_field_tag :search, '', placeholder: 'comment' %>
                <%= submit_tag 'Search', :name => nil %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= form_tag(users_path,:method => 'get', class: "serach-window") do %>
                <%= text_field_tag :search, '', placeholder: 'user' %>
                <%= submit_tag 'Search', :name => nil %>
              <% end %>
            </li>
          <% end %>
        <!--↑ログイン状態でしか出ないメニュー-->
        <% else %>
        <!--↓ログアウト状態でしか出ないメニュー-->
          <li><%= link_to "Login", login_path %></li>
        <!--↑ログアウト状態でしか出ないメニュー-->
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag('favicon.png') %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>